### ISSUE TITLE
Setting Values in the On Screen Settings Menu not working

### ISSUE THREAD

**Issue by Witzman** [aleixjf/SupremeEdition#1]
I found the settings menu (shift - uppest button on right side of display), i can scroll in the lists with the browse button but not select anything. How to push button there? Browse-Push not working - not yet implemented?
I have the issue with the menu, when trying to change the displayed key (Camelot/dinamic) it does not change anything, when i push the button.

**Comment by aleixjf** [comment]
Hi! Keep in mind that there are many functionalities which still need to be implemented! I'll try to make it more obvious for the next release those which already work, and those which don't! That's the reason why pressing push doesn't seem to work, but it does. I still need to do progress with this menu

**Comment by Witzman** [comment]
perfect, just want to try to collect my issues here instead of forum :)
